import { Theme } from '@rainbow-me/rainbowkit';

export const vaultaRainbowTheme: Theme = {
  blurs: {
    modalOverlay: 'blur(4px)',
  },
  colors: {
    accentColor: '#FFE500',
    accentColorForeground: '#0A0A0A',
    actionButtonBorder: '#0A0A0A',
    actionButtonBorderMobile: '#0A0A0A',
    actionButtonSecondaryBackground: '#FFFFFF',
    closeButton: '#0A0A0A',
    closeButtonBackground: '#FFFFFF',
    connectButtonBackground: '#FFE500',
    connectButtonBackgroundError: '#FF4D4D',
    connectButtonInnerBackground: '#FFE500',
    connectButtonText: '#0A0A0A',
    connectButtonTextError: '#FFFFFF',
    connectionIndicator: '#0B7B5E',
    downloadBottomCardBackground: '#FFFFFF',
    downloadTopCardBackground: '#F5F0E8',
    error: '#FF4D4D',
    generalBorder: '#0A0A0A',
    generalBorderDim: '#0A0A0A',
    menuItemBackground: '#F5F0E8',
    modalBackdrop: 'rgba(0, 0, 0, 0.5)',
    modalBackground: '#FFFFFF',
    modalBorder: '#0A0A0A',
    modalText: '#0A0A0A',
    modalTextDim: '#888888',
    modalTextSecondary: '#888888',
    profileAction: '#F5F0E8',
    profileActionHover: '#FFE500',
    profileForeground: '#F5F0E8',
    selectedOptionBorder: '#0A0A0A',
    standby: '#FFE500',
  },
  fonts: {
    body: 'inherit',
  },
  radii: {
    actionButton: '0px',
    connectButton: '0px',
    menuButton: '0px',
    modal: '0px',
    modalMobile: '0px',
  },
  shadows: {
    connectButton: '4px 4px 0px 0px #0A0A0A',
    dialog: '8px 8px 0px 0px #0A0A0A',
    profileDetailsAction: '4px 4px 0px 0px #0A0A0A',
    selectedOption: '4px 4px 0px 0px #0A0A0A',
    selectedWallet: '4px 4px 0px 0px #0A0A0A',
    walletLogo: '2px 2px 0px 0px #0A0A0A',
  },
};
